[workspace]
resolver = "3"
members = ["crates/cenix-core", "crates/cenix-ffi", "crates/uniffi-bindgen"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/caniko/cenix"
version = "0.1.0"

[workspace.dependencies]
cenix-core = { path = "crates/cenix-core", version = "0.1.0" }
quick-xml = "0.41"
serde = "1"
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
uniffi = "0.29.5"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
