[workspace]
resolver = "3"
members = ["crates/cenix-core", "crates/cenix-jni"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/caniko/cenix"
version = "0.1.0"

[workspace.dependencies]
cenix-core = { path = "crates/cenix-core" }
jni = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
