[package]
name = "cenix-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "UniFFI boundary for Cenix"

[lib]
name = "cenix_ffi"
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[dependencies]
cenix-core.workspace = true
thiserror.workspace = true
uniffi.workspace = true
